spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/auth_study_db
    username: root
    password: 1q2w3e4r!

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: con.korit.authstudy.mapper.dto

jwt:
  secret: 90d247005c8acb3d579721d3adfbbad9abe2e1f6c5e97398dcb7e3bb36c4aebf